# NUMPY

In [1]:
import numpy as np

In [2]:
l = [[1402,191],[1371,821],[949,1437]]

In [3]:
arr_l = np.array(l)
arr_l

array([[1402,  191],
       [1371,  821],
       [ 949, 1437]])

# INDEX MANIPULATION

In [4]:
arr_l[0][0]

1402

In [5]:
arr_l[0][1]

191

In [6]:
arr_l[2][1]

1437

In [7]:
arr_l[3][3] # doesnot exist error

IndexError: index 3 is out of bounds for axis 0 with size 3

In [8]:
y = [460,232,315,178]
y_arr = np.array(y).reshape(4,1)
y_arr

array([[460],
       [232],
       [315],
       [178]])

In [9]:
y_arr[0]

array([460])

In [10]:
y_arr[1]

array([232])

# Matrix Addition

In [11]:
A = [[1,0],[2,5],[3,1]]
B =  [[4,0.5],[2,5],[0,1]]

In [12]:
A_arr = np.array(A).reshape(3,2)
B_arr = np.array(B).reshape(3,2)

In [13]:
print('A array\n',A_arr)

A array
 [[1 0]
 [2 5]
 [3 1]]


In [14]:
print('B array\n',B_arr)

B array
 [[4.  0.5]
 [2.  5. ]
 [0.  1. ]]


In [15]:
A_arr + B_arr

array([[ 5. ,  0.5],
       [ 4. , 10. ],
       [ 3. ,  2. ]])

In [16]:
np.add(A_arr,B_arr)

array([[ 5. ,  0.5],
       [ 4. , 10. ],
       [ 3. ,  2. ]])

Addittion of 2 matrix can be done only if both matrix are of same shape

# Matrix Scalar Multiplication

In [17]:
A = [[1,0],[2,5],[3,1]]
B = [[4,0],[6,3]]

In [18]:
A_arr = np.array(A).reshape(3,2)
B_arr = np.array(B).reshape(2,2)

In [19]:
A_arr

array([[1, 0],
       [2, 5],
       [3, 1]])

In [20]:
B_arr

array([[4, 0],
       [6, 3]])

In [21]:
3 * A_arr 

array([[ 3,  0],
       [ 6, 15],
       [ 9,  3]])

In [22]:
np.multiply(3,A_arr)

array([[ 3,  0],
       [ 6, 15],
       [ 9,  3]])

In [23]:
 B_arr/4 

array([[1.  , 0.  ],
       [1.5 , 0.75]])

In [24]:
np.multiply(B_arr,1/4) 

array([[1.  , 0.  ],
       [1.5 , 0.75]])

Combining operations

In [25]:
A_arr = np.array([1,4,2]).reshape(3,1)
B_arr = np.array([0,0,5]).reshape(3,1)
C_arr = np.array([3,0,2]).reshape(3,1)

In [26]:
3*A_arr + B_arr - C_arr/3

array([[ 2.        ],
       [12.        ],
       [10.33333333]])

In [27]:
a = np.multiply(3,A_arr)
b = np.multiply(C_arr,1/3)

In [28]:
np.subtract(np.add(a,B_arr),b)

array([[ 2.        ],
       [12.        ],
       [10.33333333]])

# Matrix Multiplication

In [29]:
A = [[1,3],[4,0],[2,1]]
B = [1,5]
A_arr = np.array(A).reshape(3,2)
B_arr = np.array(B).reshape(2,1)

In [30]:
A_arr

array([[1, 3],
       [4, 0],
       [2, 1]])

In [31]:
B_arr

array([[1],
       [5]])

Matrix multiplication is also called dot product

In [32]:
np.dot(A_arr , B_arr)

array([[16],
       [ 4],
       [ 7]])

# Inverse

In [33]:
A = [[3,4],[2,16]]
A_arr = np.array(A).reshape(2,2)

In [34]:
A_inv = np.linalg.inv(A_arr)

In [35]:
np.dot(A,A_inv)

array([[1., 0.],
       [0., 1.]])

In [36]:
A = [[1,1],[1,1]]
A_arr = np.array(A).reshape(2,2)

In [37]:
A_arr

array([[1, 1],
       [1, 1]])

In [38]:
A_inv = np.linalg.inv(A_arr)

LinAlgError: Singular matrix

Singular matrix does not has inverse

# Transpose

In [39]:
A_arr = np.array([[1,2,0],[3,5,9]]).reshape(2,3)

In [40]:
A_arr

array([[1, 2, 0],
       [3, 5, 9]])

In [41]:
AT = A_arr.transpose()

In [42]:
AT

array([[1, 3],
       [2, 5],
       [0, 9]])

# Matrix SUM

In [43]:
A_arr = np.array([[1,2,0],[3,5,9]]).reshape(2,3)

In [44]:
A_arr

array([[1, 2, 0],
       [3, 5, 9]])

In [45]:
np.sum(A_arr) # sum of matrix

20

In [46]:
np.sum(A_arr,axis=0) # add rows wise

array([4, 7, 9])

In [47]:
np.sum(A_arr, axis=1) #add column wise

array([ 3, 17])

# Practical e.g.

In [48]:
house_size = np.array([[2104,1416,1534,852]]).reshape(4,1)

In [49]:
H = np.array([[-40,0.25]]).reshape(2,1)

In [50]:
ones = np.ones((4,1))

In [51]:
X = np.concatenate((ones,house_size),axis =1)

In [52]:
np.dot(X,H)

array([[486. ],
       [314. ],
       [343.5],
       [173. ]])